config/routes.rb
Rails.application.routes.draw do
  root to: "informations#index"

  # グループウェア系
  resources :projects, only: [:index, :show] do
    get '/tasks',  to: 'projects#show2'
  end

  # 生徒管理
  # resources :students, only: [:index, :new, :create]
  resources :annual_students, only: [:index, :edit]
  resources :freshmans, only: [:index, :new, :create]

  # 欠席連絡取得
  resources :contacts, only: [:index, :show]

  # 管理者系 「/admin」から始まるURIを権限チェック
  scope :admin do
    # ユーザー管理系
    resources :users, only: [:index, :new, :create, :edit, :update]
      get  'users/select', to: 'users#select', as: 'user_select'
      post 'users/switch', to: 'users#switch', as: 'user_switch'
    # 教員管理
    resources :teachers,          only: [:index, :new, :create] do
      resources :annual_teachers,   only: [:new, :create]
      get   '/annual_teachers/edit',   to: 'annual_teachers#edit',   as: 'edit_annual_teacher'
      patch '/annual_teachers/update', to: 'annual_teachers#update', as: 'annual_teacher'
    end
    resources :annual_teachers,   only: [:index]
    # マスタメンテ系
    resources :years,             only: [:index, :new, :create]
    resources :terms,             only: [:index, :new, :create]
    resources :year_terms,        only: [:index, :new, :create]
    resources :subject_areas,     only: [:index, :new, :create]
    resources :subjects,          only: [:index, :new, :create]
    # resources :subject_areas, only: [:index, :new, :create] do
    #   resources :subjects, param: :id, only: [:index]
    # end
    resources :jobs,              only: [:index, :new, :create]
    resources :sections,          only: [:index, :new, :create]
    resources :responsibilities,  only: [:index, :new, :create]
  end

  # ログイン
  devise_for :users,
  only: [:sessions],
  controllers: {
    sessions: 'users/sessions'
  }

  # 欠席連絡・出欠席管理
  resources :contacts, only: [:index]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # role が admin のユーザーはモデルの操作を行うことができて管理者画面を閲覧可能
    if user.has_role?(:admin)
      can :manage, :all
      can :access_admin_page, :all

    # role が manager のユーザーはモデルの操作を行うことができるが、管理者画面は閲覧不可能
    elsif user.has_role?(:manager)
      can :manage, :all
      cannot :access_admin_page, :all

    # role が read_only のユーザーはモデルの操作を行うことができず閲覧のみ可能、管理者画面は閲覧不可能
    elsif user.has_role?(:read_only)
      can :read, :all
      cannot :access_admin_page, :all

    # role を持っていないユーザーは全ての画面が閲覧不可能
    else
      cannot :read, :all
    end
  end
end

app/models/annual_student.rb
class AnnualStudent < ApplicationRecord
  belongs_to :student
end

app/models/annual_teacher.rb
class AnnualTeacher < ApplicationRecord
  belongs_to :year
  belongs_to :teacher
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :task
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :responsibilities
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :annual_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :subject_area
end

app/models/subject_area.rb
class SubjectArea < ApplicationRecord
  has_many :subjects
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user,      optional: true
  belongs_to :subjects,  optional: true
  has_many :annual_teachers
end

app/models/term.rb
class Term < ApplicationRecord
  has_many :year_terms
  has_many :users,  through: :year_term
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # validatableにはemailのuniquenessのバリデーションが定義されているので除外
  # 自前でvalidationをいれること！
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable#, :validatable

  has_many   :users_role
  belongs_to :year_term
  has_one    :year,  through: :year_term
  has_one    :term,  through: :year_term
  has_one    :teacher
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :year_terms
  has_many :user,  through: :year_term
  has_many :annual_teachers
end

app/models/year_term.rb
class YearTerm < ApplicationRecord
  belongs_to :year
  belongs_to :term
  has_many   :users
end

app/controllers/freshmans_controller.rb
class FreshmansController < ApplicationController
  before_action :set_logined_term

  def index
    # 次年度を紐付けなければならないので、これではダメ
    @freshman_students = AnnualStudent.where(year_id: @logined_term.year.id).includes(:student)
  end

  def new
    # 次年度を紐付けなければならないので、これではダメ
    @freshman_students = AnnualStudent.where(year_id: @logined_term.year.id).includes(:student)
    @freshman_student = FreshmanStudent.new
  end

  def create
    @freshman_student = FreshmanStudent.new(freshman_params)
    # if @freshman_student.valid?
      @freshman_student.save
      redirect_to root_path
    # else
    #   render :new
    # end
  end

  private

  def set_logined_term
    @logined_term = User.includes([:year,:term,:year_term]).find(current_user.id)
  end

  def freshman_params
    params.require(:freshman_student)
          .permit(:code, :last_name, :first_name, :last_name_reading, :first_name_reading, :sex, :school_grade)
          .merge(year_id: @logined_term.year.id) # 次年度を紐付けなければならないので、これではダメ
  end
end

app/helpers/freshmans_helper.rb
module FreshmansHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/freshmans/index.html.erb
<%= render "shared/navbar" %>
<div class="split w-100 vh-100">
  <%= render 'freshmans/shared/freshman_list', {freshmans: @freshman_students} %>
  <%#= render 'freshmans/shared/freshman_list' %>

  <div class="split-main w-100-fixed-250 h-100 bg-gray-200 p-3">
    ここに表示されます。<br>
    個別入力用の「新規登録」は他の登録画面と同じ<br>
    「一覧／編集」は取得してスプレッドシートに表示させる<br>
    変更・削除フラグ用のカラムを1つ追加して、更新ボタンでpostする<br>
    「CSV入出力」では、雛形生成から送信での一括登録機能実装<br>
    <br>
    …と思ったが、ひとまずレイアウトに関しては後回しにして、<br>
    CRUD機能を優先して実装していくことにする
  </div>
</div>

app/views/freshmans/new.html.erb
<%= render "shared/navbar" %>
<div class="split w-100 vh-100">
  <%#= render 'freshmans/shared/freshman_list', {freshmans: @freshmans} %>
  <%= render 'freshmans/shared/freshman_list' %>

  <div class="split-main w-100-fixed-250 h-100 bg-gray-200 p-3">
    <%= form_with model: @freshman_student, url: freshmans_path, class: "row gx-5 gy-3 m-3" do |f| %>
      <div class="col-md-2 pe-3 my-3">
        <%= f.label :code, "コード", class: "form-label text-nowrap" %>
        <%= f.text_field :code, autofocus: true, autocomplete: "code", class: "form-control" %>
      </div>
      <div class="col-md-10">
      </div>

      <div class="col-md-4 pe-3 my-3">
        <%= f.label :last_name, "姓", class: "form-label" %>
        <%= f.text_field :last_name, autocomplete: "last_name", class: "form-control" %>
      </div>
      <div class="col-md-4 ps-3 my-3">
        <%= f.label :first_name, "名", class: "form-label" %>
        <%= f.text_field :first_name, autocomplete: "first_name", class: "form-control" %>
      </div>
      <div class="col-md-4">
      </div>

      <div class="col-md-4 pe-3 my-3">
        <%= f.label :last_name_reading, "せい", class: "form-label" %>
        <%= f.text_field :last_name_reading, autocomplete: "last_name_reading", class: "form-control" %>
      </div>
      <div class="col-md-4 ps-3 my-3">
        <%= f.label :first_name_reading, "めい", class: "form-label" %>
        <%= f.text_field :first_name_reading, autocomplete: "first_name_reading", class: "form-control" %>
      </div>
      <div class="col-md-4">
      </div>

      <div class="col-md-2 pe-3 my-3">
        <%= f.label :sex, "性別", class: "form-label" %>
        <%= f.text_field :sex, autocomplete: "sex", class: "form-control" %>
      </div>
      <div class="col-md-3 ps-3 my-3">
        <%= f.label :school_grade, "新学年", class: "form-label" %>
        <%= f.text_field :school_grade, autocomplete: "school_grade", class: "form-control" %>
      </div>
      <div class="col-md-7">
      </div>

      <div class="col-12">
        <button type="submit" class="btn btn-primary">登録</button>
      </div>
    <% end %>
  </div>
</div>